Repository ucsb-cs156-s25/proj-frontiers-s25-09, pull requests merged in 2025-06, with the labels that each got.

#29 AK - CoursesController: New Controller Method(Backend Endpoint)
  src/main/java/edu/ucsb/cs156/frontiers/controllers/CoursesController.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/CourseRepository.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/CoursesControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/StudentCourseViewTests.java
  src/test/java/edu/ucsb/cs156/frontiers/models/RosterStudentDTOTests.java
Labels: Ready-For-Staff

#58 AK - application-development.properties Adjustment #1
  src/main/resources/application-development.properties
Labels: 10

#56 MB-issue01-v2small, Fixed 403 Issue for Google Github Login for Null
  frontend/src/main/components/Nav/GithubLogin.js
  frontend/src/main/components/Nav/GoogleLogin.js
  frontend/src/tests/components/Nav/GithubLogin.test.js
  frontend/src/tests/components/Nav/GoogleLogin.test.js
Labels: 10, Merge Candidate-CI

#49 MB- add roster student table, stories, and tests
  frontend/src/fixtures/rosterStudentFixtures.js
  frontend/src/main/components/RosterStudent/RosterStudentTable.js
  frontend/src/main/utils/RosterStudentUtils.js
  frontend/src/stories/components/RosterStudent/RosterStudentTable.stories.js
  frontend/src/tests/components/RosterStudent/RosterStudentTable.test.js
  frontend/src/tests/utils/rosterStudent.test.js
Labels: 10, Merge Candidate-CI
