Repository ucsb-cs156-s25/proj-frontiers-s25-09, pull requests merged in 2025-05, with the labels that each got.

#30 ra-RoleEmailTable, utility file, tests and stories
  frontend/src/fixtures/roleEmailFixtures.js
  frontend/src/main/components/Users/RoleEmailTable.js
  frontend/src/main/utils/RoleEmailUtils.js
  frontend/src/stories/components/Users/RoleEmailTable.stories.js
  frontend/src/tests/components/Users/RoleEmailTable.test.js
  frontend/src/tests/utils/roleEmail.test.js
Labels: 10

#31 ra-RoleEmailForm, tests and stories
  frontend/src/main/components/Users/RoleEmailForm.js
  frontend/src/stories/components/Users/RoleEmailForm.stories.js
  frontend/src/tests/components/Users/RoleEmailForm.test.js
Labels: 10, Merge Candidate-CI

#37 JS - added update crud operation for student roster and tests
  src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/ApiControllerTests.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: 10, Merge Candidate-CI

#38 jz-created entity, repository, and db migration files for Admins Table
  src/main/java/edu/ucsb/cs156/frontiers/entities/Admin.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/AdminRepository.java
  src/main/resources/db/migration/changes/007-create-Admins.json
Labels: 5, Merge Candidate-CI

#44 JS - added delete crud operation for student roster and tests
  src/main/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsController.java
  src/main/java/edu/ucsb/cs156/frontiers/entities/Course.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/RosterStudentsControllerTests.java
Labels: 10, Merge Candidate-CI

#45 Jz - admin controller
  src/main/java/edu/ucsb/cs156/frontiers/controllers/AdminController.java
  src/main/java/edu/ucsb/cs156/frontiers/controllers/ApiController.java
  src/main/resources/db/migration/changes/007-create-Admins.json
  src/test/java/edu/ucsb/cs156/frontiers/controllers/AdminControllerTests.java
Labels: 10, Merge Candidate-CI

#50 MB-RosterStudentForm-v2, frontend student form, stories, and tests
  frontend/src/fixtures/rosterStudentFixtures.js
  frontend/src/main/components/RosterStudent/RosterStudentForm.js
  frontend/src/stories/components/RosterStudent/RosterStudentForm.stories.js
  frontend/src/tests/components/RosterStudent/RosterStudentForm.test.js
Labels: 10, Merge Candidate-CI

#42 ra-AdminsIndexPage, tests and stories
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Admins/AdminsIndexPage.js
  frontend/src/stories/pages/Admins/AdminsIndexPage.stories.js
  frontend/src/tests/pages/Admins/AdminsIndexPage.test.js
Labels: 10, Merge Candidate-CI

#43 ra-AdminCreatePage, tests and stories
  frontend/src/App.js
  frontend/src/main/pages/Admins/AdminsCreatePage.js
  frontend/src/stories/pages/Admins/AdminsCreatePage.stories.js
  frontend/src/tests/pages/Admins/AdminsCreatePage.test.js
Labels: 10, Merge Candidate-CI

#47 AK - Instructors Table(Entity, Repository, db-Migration)
  src/main/java/edu/ucsb/cs156/frontiers/entities/Instructor.java
  src/main/java/edu/ucsb/cs156/frontiers/repositories/InstructorRepository.java
  src/main/resources/db/migration/changes/009-Instructors-create.json
Labels: 5, Merge Candidate-CI

#48 Jz - instructor controller and tests
  src/main/java/edu/ucsb/cs156/frontiers/controllers/InstructorController.java
  src/test/java/edu/ucsb/cs156/frontiers/controllers/InstructorControllerTests.java
Labels: 10, Merge Candidate-CI
